### ISSUE TITLE
[FEATURE] Mouse Support

### ISSUE THREAD

**Issue by agent-LuluDodo** [agent-LuluDodo/RebindMyKeys#5]
## ETA
idk, if I'm motivated maybe in a few days if not in a few months ;)

## TODO
- [x] Rewrite internal handling of KeyBindings and Conflicts to allow keybinds specific to one screen or something similar
- [x] Find the place in Mouse.class to mixin into
- [x] Use the implementations from Keyboard.onKey() for better mod support
- [x] Mouse support for Vanilla KeyBindings
- [x] Fix weird quirk of 1.20-1.20.3 that mouse clicks on EntryListWidgets always return true, which breaks my mouse implementation (technically usable, but not as fun as in 1.20.4)

## Note
TODO#3 could be archived by setting a flag and then calling Keyboard.onKey(). Then a mixin runs the implementation which should be run. (jank, but probably my best bet)

**Comment by agent-LuluDodo** [comment]
This went better than expected :)

**Comment by agent-LuluDodo** [comment]
TODO: Fix weird quirk of 1.20-1.20.3 that mouse clicks on EntryListWidgets always return true, which breaks my mouse implementation (technically usable, but not as fun as in 1.20.4)

**Comment by agent-LuluDodo** [comment]
The version with mouse support is here: https://modrinth.com/mod/rebindmykeys/version/3.0+alpha
3.0 will release when I'm finished with all the features I want to implement :)
